# Global variables section
variables:  
  vyos_wan_ip: "192.168.1.1"
  proxmox_hostname: "pve.homelab"
# Module configurations
modules: 
  - name: Proxmox
    vars:
      hostname: {{ proxmox_hostname }}
  - name: VyOS
    vars:
      wan_ip: {{ vyos_wan_ip }} 
