# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".ruff_cache",
    ".vscode",
    "__pycache__",
    "venv",
]

line-length = 420
indent-width = 4

[lint]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "tab"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
