- hosts: bootstrapper
  connection: local
  tasks:
    - name: Install FAI server dependencies
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - fai-quickstart
          - fai-doc
          - fai-server
          - isc-dhcp-server
          - tftpd-hpa
          - nfs-kernel-server
          - syslinux-common

    - name: Create pxeusers group
      group:
        name: pxeusers
        state: present

    - name: Add fai and root to pxeusers group
      user:
        name: "{{ item }}"
        groups: pxeusers
        append: true
      loop:
        - fai
        - root

    - name: Update /etc/hosts file
      include_role:
        name: configure_etc_hosts
      vars:
        ip_address: "{{ bootstrapper_ip | ansible.utils.ipaddr('address') }}"
        hostname: "{{ bootstrapper_hostname }}"
        remove: false

    - name: Create Directory For TFTP and Network Boot Configuration
      file:
        path: /srv/tftp/fai/pxelinux.cfg
        state: directory
        owner: fai
        group: pxeusers
        mode: 0644

    - name: Template configuration files
      include_role:
        name: configure_fai

    - name: Confirm PXE Configuration Files Exist
      file:
        path: "/srv/tftp/fai/{{ item }}"
        state: file
      failed_when: false
      loop:
        - pxelinux.0
        - syslinux.efi

    - name: Cehcking if we need the default configuration files
      stat:
        path: /srv/fai/config/.done
      register: default_config_copied

    - name: Copy FAI Configuration Files
      copy:
        src: /usr/share/doc/fai-doc/examples/simple/
        dest: /srv/fai/config/
        mode: preserve
      when: not default_config_copied.stat.exists

    - name: Touch the .done file
      file:
        path: /srv/fai/config/.done
        state: touch
        mode: 0600
        owner: root
        group: root
      when: not default_config_copied.stat.exists

    - name: Create default disk partition layout
      blockinfile:
        path: /srv/fai/config/disk_config/DEFAULT
        block: |
          disk_config disk1 disklabel:gpt fstabkey:uuid align-at:1M

          p=efi    /boot/efi 512M vfat rw
          p=boot   /boot    200  ext4 rw,noatime
          p=system -        4G-  -    -

          disk_config lvm

          vg vg1 disk1.3
          vg1-root    /      3G-     ext4   noatime,rw
          vg1-swap    swap   200-4G  swap   sw
        owner: fai
        group: pxeusers
        mode: 0644
        create: true

    - name: Create post install script
      copy:
        dest: /srv/fai/config/scripts/DEBIAN/50-ansible-setup
        content: |
          #!/bin/bash
          $ROOTCMD adduser --disabled-password --shell /bin/bash --gecos "ansible user" ansible
          $ROOTCMD usermod -aG sudo ansible
          $ROOTCMD mkdir -p /home/ansible/.ssh
          echo "{{ ansible_public_key }}" >> /target/home/ansible/.ssh/authorized_keys
          $ROOTCMD chmod 644 /home/ansible/.ssh/authorized_keys
          $ROOTCMD chown -R ansible:ansible /home/ansible/
          echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /target/etc/sudoers.d/ansible
          sed -i '/PasswordAuthentication/d' /target/etc/ssh/sshd_config
          echo "PasswordAuthentication no" >> /target/etc/ssh/sshd_config
          sed -i '/ChallengeResponseAuthentication/d' /target/etc/ssh/sshd_config
          echo "ChallengeResponseAuthentication no" >> /target/etc/ssh/sshd_config
        owner: fai
        group: pxeusers
        mode: 0777

    - name: Restart PXE Services
      include_role:
        name: restart_pxe_services
