- name: Template FAI configuration
  template:
    src: fai.conf.j2
    dest: /etc/fai/fai.conf

- name: Template NFS configuration
  template:
    src: nfsroot.conf.j2
    dest: /etc/fai/nfsroot.conf

- name: Template Apt Sources configuration
  template:
    src: sources.list.j2
    dest: /etc/fai/apt/sources.list

- name: Remove Default Lines In /etc/default/isc-dhcp-server
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: '^(INTERFACESv4|INTERFACESv6)=.*'
    state: absent

- name: Properly Configure /etc/default/isc-dhcp-server
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: "INTERFACESv4={{ bootstrapper_mgmt_interface }}"
    line: "INTERFACESv4={{ bootstrapper_mgmt_interface }}"
    state: present
    create: yes

- name: Template DHCP configuration
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf

- name: Template TFTP configuration
  template:
    src: tftpd-hpa.j2
    dest: /etc/default/tftpd-hpa

- name: Restart PXE Services
  include_role:
    name: restart_pxe_services
